UPDATE `sysprops` SET `V` = '2' WHERE `K` = 'dbstructure'; 
ALTER TABLE resinfo DROP COLUMN `XML`;
ALTER TABLE tradeform ADD COLUMN `UPR` DECIMAL(9,4) DEFAULT NULL NULL AFTER `version`;
ALTER TABLE tradeform ADD COLUMN `expDaysWhenOpen` INT UNSIGNED DEFAULT NULL NULL AFTER `UPR`;
ALTER TABLE medstock ADD COLUMN `expire` DATETIME DEFAULT NULL NULL AFTER `UPR`;
