INSERT INTO `homes` (`eid`, `name`, `str`, `zip`, `city`, `tel`, `fax`,`color`,`active`) VALUES ('home1', 'OPDE Haus', 'Strasse', '11111', 'Ort', '00000-00000', '00000-00000','3333ff','1');
INSERT INTO `floors` (`floorid`,`homeid`, `name`, `level`, `lift`, `version`) VALUES ('1','home1', 'Erdgeschoss', '0', '1', '1'); 
INSERT INTO `rooms` (`RID`, `floorid`, `Text`, `Single`, `Bath`, `active`, `version`) values('1','1','1','1','1','1','0');
INSERT INTO `station` (`statid`,`eid`, `name`, `version`) VALUES ('1','home1', 'Station 1','0');
INSERT INTO `users` (Vorname, Nachname, UKennung, STATUS, MD5PW, version, cipherid) VALUES ('OPDE','Admin','admin',2,'notyet','0',ROUND((RAND() * (10000))+1));
INSERT INTO `member` (`UKennung`, `GKennung`) VALUES ('admin', 'admin');
INSERT INTO `member` (`UKennung`, `GKennung`) VALUES ('admin', 'everyone');
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('FM','00:00',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('MO','06:30',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('MI','11:30',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('NM','13:15',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('AB','17:30',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('NA','21:00',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('apv_korridor','20',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('dbstructure','12',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('calc.medi.upr1','false',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('calc.medi.other','false',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('bhp_max_minutes_to_withdraw','30',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('cash_pagebreak_after_element_no','30',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('dfn_max_minutes_to_withdraw','30',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('EARLY_BGITEM','D0E6FF',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('EARLY_BGSHIFT','62A9FF',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('EARLY_FGITEM','62A9FF',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('EARLY_FGSHIFT','ECF4FF',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('LATE_BGITEM','DBEADC',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('LATE_BGSHIFT','59955C',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('LATE_FGITEM','59955C',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('LATE_FGSHIFT','F3F8F4',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('ONDEMAND_BGITEM','EEEECE',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('ONDEMAND_BGSHIFT','D1D17A',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('ONDEMAND_FGITEM','D1D17A',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('ONDEMAND_FGSHIFT','F5F5E2',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('OUTCOME_BGSHIFT','404040',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('OUTCOME_FGSHIFT','c0c0c0',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('VERY_EARLY_BGITEM','FFC8E3',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('VERY_EARLY_BGSHIFT','FF62B0',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('VERY_EARLY_FGITEM','FF62B0',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('VERY_EARLY_FGSHIFT','FFECF5',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('VERY_LATE_BGITEM','FFA8FF',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('VERY_LATE_BGSHIFT','990099',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('VERY_LATE_FGITEM','990099',NULL);
INSERT INTO `sysprops` (`K`, `V`, `UKennung`) VALUES('VERY_LATE_FGSHIFT','FFE3FF',NULL);
