/*
 * OffenePflege
 * Copyright (C) 2008 Torsten Löhr
 * This program is free software; you can redistribute it and/or modify it under the terms of the 
 * GNU General Public License V2 as published by the Free Software Foundation
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even 
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 * Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with this program; if not, write to 
 * the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110, USA
 * www.offene-pflege.de
 * ------------------------ 
 * Auf deutsch (freie Übersetzung. Rechtlich gilt die englische Version)
 * Dieses Programm ist freie Software. Sie können es unter den Bedingungen der GNU General Public License, 
 * wie von der Free Software Foundation veröffentlicht, weitergeben und/oder modifizieren, gemäß Version 2 der Lizenz.
 *
 * Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen von Nutzen sein wird, aber 
 * OHNE IRGENDEINE GARANTIE, sogar ohne die implizite Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN 
 * BESTIMMTEN ZWECK. Details finden Sie in der GNU General Public License.
 *
 * Sie sollten ein Exemplar der GNU General Public License zusammen mit diesem Programm erhalten haben. Falls nicht, 
 * schreiben Sie an die Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110, USA.
 * 
 */
package op.bw.admin;

import java.awt.event.ActionEvent;
import java.awt.event.ComponentEvent;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import op.share.bwinfo.BWInfo;
import op.share.bwinfo.PnlBWInfo;
import op.OPDE;
import op.tools.SYSCalendar;
import op.tools.SYSConst;
import op.tools.SYSTools;

/**
 *
 * @author  tloehr
 */
public class FrmBWAttr extends javax.swing.JFrame {

    public static final int TAB_DATEN = 0;
    public static final int TAB_LISTEN = 1;
    private String currentBW;
    private ArrayList heimaufenthalte;
    private PnlBWInfo pnlData;
    private boolean initphase;

    /** Creates new form FrmBWAttr */
    public FrmBWAttr() {
        initphase = true;
        currentBW = "";
        initComponents();

        jtpMain.setEnabledAt(TAB_LISTEN, false);

        this.setTitle(SYSTools.getWindowTitle("Bewohnerverwaltung"));
        setVisible(true);
        txtBW.requestFocus();
        jtpMain.setSelectedIndex(TAB_DATEN);
        btnNew.setEnabled(false);
        btnEditBW.setEnabled(false);
        btnPrint.setEnabled(false);
        initphase = false;
    //initListModels();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAnzeige = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNewBW = new javax.swing.JButton();
        btnEditBW = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();
        btnOut = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jtpMain = new javax.swing.JTabbedPane();
        pnlAktuell = new javax.swing.JPanel();
        jspData = new javax.swing.JScrollPane();
        txtBW = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        pnlList = new javax.swing.JPanel();

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setFloatable(false);

        btnNewBW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artwork/22x22/add_group.png"))); // NOI18N
        btnNewBW.setText("Neue(r) BW");
        btnNewBW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewBWActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNewBW);

        btnEditBW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artwork/22x22/edit_group.png"))); // NOI18N
        btnEditBW.setText("BW bearbeiten");
        btnEditBW.setEnabled(false);
        btnEditBW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBWActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditBW);

        btnIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artwork/22x22/user_active.png"))); // NOI18N
        btnIn.setText("Heimaufnahme");
        btnIn.setEnabled(false);
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });
        jToolBar1.add(btnIn);

        btnOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artwork/22x22/user_inactive.png"))); // NOI18N
        btnOut.setText("Auszug/Tod");
        btnOut.setEnabled(false);
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOut);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artwork/22x22/filenew.png"))); // NOI18N
        btnNew.setText("Neu");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNew);

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artwork/22x22/printer.png"))); // NOI18N
        btnPrint.setText("Drucken");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPrint);

        jtpMain.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jtpMain.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtpMainStateChanged(evt);
            }
        });

        txtBW.setToolTipText("Sie können hier Teile des Nachnamens oder die Kennung eingeben.");
        txtBW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBWActionPerformed(evt);
            }
        });
        txtBW.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBWFocusGained(evt);
            }
        });

        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artwork/16x16/search.png"))); // NOI18N
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnlAktuellLayout = new org.jdesktop.layout.GroupLayout(pnlAktuell);
        pnlAktuell.setLayout(pnlAktuellLayout);
        pnlAktuellLayout.setHorizontalGroup(
            pnlAktuellLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlAktuellLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlAktuellLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jspData, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                    .add(pnlAktuellLayout.createSequentialGroup()
                        .add(txtBW, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnFind)))
                .addContainerGap())
        );
        pnlAktuellLayout.setVerticalGroup(
            pnlAktuellLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlAktuellLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlAktuellLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnFind)
                    .add(txtBW, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(jspData, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpMain.addTab("Aktuell", pnlAktuell);

        org.jdesktop.layout.GroupLayout pnlListLayout = new org.jdesktop.layout.GroupLayout(pnlList);
        pnlList.setLayout(pnlListLayout);
        pnlListLayout.setHorizontalGroup(
            pnlListLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 773, Short.MAX_VALUE)
        );
        pnlListLayout.setVerticalGroup(
            pnlListLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 452, Short.MAX_VALUE)
        );

        jtpMain.addTab("Listen", pnlList);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jToolBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jtpMain, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                .add(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jtpMain, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpMain.getAccessibleContext().setAccessibleName("Einzelanzeige");

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-812)/2, (screenSize.height-565)/2, 812, 565);
    }// </editor-fold>//GEN-END:initComponents
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
//        boolean preview = (evt.getModifiers() & ActionEvent.SHIFT_MASK) > 0;
//        boolean dialog = (evt.getModifiers() & ActionEvent.CTRL_MASK) > 0;
        pnlData.print();
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnEditBWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBWActionPerformed
        new DlgBW(this, DlgBW.MODE_EDIT, currentBW).showDialog();
        txtBW.setText(currentBW);
        btnFind.doClick();
    }//GEN-LAST:event_btnEditBWActionPerformed

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed
        Date minDate = this.pnlData.getBWInfo().getVonHauf();
        new DlgBWOut(this, minDate, this.pnlData.getBWInfo().getHaufBWINFOID());
        reloadDisplay();
    }//GEN-LAST:event_btnOutActionPerformed

    private void btnNewBWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewBWActionPerformed
        String newbwkennung = new DlgBW(this, DlgBW.MODE_NEW, "").showDialog();
        if (newbwkennung != null) {
            txtBW.setText(newbwkennung);
            btnFind.doClick();
        }
    }//GEN-LAST:event_btnNewBWActionPerformed

    public void cleanup() {
        SYSTools.unregisterListeners(this);
        if (heimaufenthalte != null) {
            heimaufenthalte.clear();
        }
    }

    public void dispose() {

        cleanup();
        super.dispose();
    }

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        Date minDate = SYSConst.DATE_VON_ANFANG_AN;
        if (this.pnlData.getBWInfo().getBisHauf() != null) {
            minDate = SYSCalendar.addDate(this.pnlData.getBWInfo().getBisHauf(), 1);
        }
        DlgBWIn dlg = new DlgBWIn(this, minDate, currentBW);
        reloadDisplay();
    }//GEN-LAST:event_btnInActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        pnlData.neu();
        jspData.dispatchEvent(new ComponentEvent(jspData, ComponentEvent.COMPONENT_RESIZED));
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        txtBWActionPerformed(evt);
    }//GEN-LAST:event_btnFindActionPerformed

    private void txtBWFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBWFocusGained
        txtBW.setSelectionStart(0);
        txtBW.setSelectionEnd(txtBW.getText().length());
    }//GEN-LAST:event_txtBWFocusGained

    private void txtBWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBWActionPerformed
        String prevBW = currentBW;
        currentBW = SYSTools.findeBW(this, txtBW.getText(), OPDE.isAdmin());
        if (currentBW.equals("")) {
            JOptionPane.showMessageDialog(this, "Keine(n) passende(n) Bewohner(in) gefunden.", "Hinweis", JOptionPane.INFORMATION_MESSAGE);
            //tblTG.setModel(new DefaultTableModel());
            currentBW = prevBW;
        }
        if (!currentBW.equals("") || !prevBW.equals("")) { // Sonst kommt die Meldung "keine passenden BW..." zweimal bei nicht vorhandenen Bewohnern
            reloadDisplay();
        }
    }//GEN-LAST:event_txtBWActionPerformed

    private void jtpMainStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtpMainStateChanged
        reloadDisplay();
    }//GEN-LAST:event_jtpMainStateChanged

    private void reloadDisplay() {
        if (!initphase) {
            if (!currentBW.equals("")) {
                pnlData = new PnlBWInfo(this, BWInfo.ART_ALLES, currentBW, "Verwaltung und Stammdaten");
                jspData.setViewportView(pnlData);
                btnNew.setEnabled(true);
                btnEditBW.setEnabled(OPDE.isAdmin());
                btnPrint.setEnabled(true);
                btnIn.setEnabled(pnlData.getBWInfo().getHaufBWINFOID() == -1 || (!pnlData.getBWInfo().isAufenthalt() && !pnlData.getBWInfo().isVerstorben() && SYSCalendar.sameDay(pnlData.getBWInfo().getBisHauf(), SYSCalendar.today_date()) != 0));
                btnOut.setEnabled(pnlData.getBWInfo().isAufenthalt());
            } else {
                JOptionPane.showMessageDialog(this, "Keine(n) passende(n) Bewohner(in) gefunden.", "Hinweis", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgAnzeige;
    private javax.swing.JButton btnEditBW;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNewBW;
    private javax.swing.JButton btnOut;
    private javax.swing.JButton btnPrint;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane jspData;
    private javax.swing.JTabbedPane jtpMain;
    private javax.swing.JPanel pnlAktuell;
    private javax.swing.JPanel pnlList;
    private javax.swing.JTextField txtBW;
    // End of variables declaration//GEN-END:variables
}
