/*
 * OffenePflege
 * Copyright (C) 2011 Torsten Löhr
 * This program is free software; you can redistribute it and/or modify it under the terms of the
 * GNU General Public License V2 as published by the Free Software Foundation
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program; if not, write to
 * the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110, USA
 * www.offene-pflege.de
 * ------------------------
 * Auf deutsch (freie Übersetzung. Rechtlich gilt die englische Version)
 * Dieses Programm ist freie Software. Sie können es unter den Bedingungen der GNU General Public License,
 * wie von der Free Software Foundation veröffentlicht, weitergeben und/oder modifizieren, gemäß Version 2 der Lizenz.
 *
 * Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen von Nutzen sein wird, aber
 * OHNE IRGENDEINE GARANTIE, sogar ohne die implizite Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN
 * BESTIMMTEN ZWECK. Details finden Sie in der GNU General Public License.
 *
 * Sie sollten ein Exemplar der GNU General Public License zusammen mit diesem Programm erhalten haben. Falls nicht,
 * schreiben Sie an die Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110, USA.
 */
package op.care.sysfiles;

import java.awt.event.*;
import javax.swing.table.*;
import entity.Bewohner;
import entity.BewohnerTools;
import entity.files.SYSFiles;
import entity.files.SYSFilesTools;
import op.OPDE;
import op.care.CleanablePanel;
import op.care.FrmPflege;
import op.tools.InternalClassACL;
import op.tools.SYSTools;
import tablemodels.TMSYSFiles;
import tablerenderer.RNDHTML;

import javax.swing.*;
import java.awt.Desktop.Action;
import java.awt.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * @author tloehr
 */
public class PnlFiles extends CleanablePanel {
    // Wird für die Zuordnung beim Rechtesystem innerhalb
    // OCRights Tabelle benötigt.

    public static final String internalClassID = "nursingrecords.files";
    private JPopupMenu menu;
    private Bewohner bewohner;
    private javax.swing.JFrame parent;


    /**
     * Creates new form PnlFiles
     */
    public PnlFiles(FrmPflege pflege, Bewohner bewohner) {
        initComponents();
        this.bewohner = bewohner;
        bewohner = OPDE.getEM().find(Bewohner.class, bewohner.getBWKennung());
        this.parent = pflege;
        BewohnerTools.setBWLabel(lblBW, bewohner);
        tblFiles.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        btnNew.setEnabled(OPDE.getInternalClasses().userHasAccessLevelForThisClass(internalClassID, InternalClassACL.INSERT));

        loadTable();
    }

    @Override
    public void cleanup() {
        SYSTools.unregisterListeners(menu);
        SYSTools.unregisterListeners(this);
    }

    @Override
    public void change2Bewohner(Bewohner bewohner) {
        //To change body of implemented methods use File | Settings | File Templates.
    }

    void loadTable() {

        List<SYSFiles> files = new ArrayList<SYSFiles>(SYSFilesTools.findByBewohner(bewohner));
        Collections.sort(files);

        tblFiles.setModel(new TMSYSFiles(files));
        tblFiles.getColumnModel().getColumn(0).setCellRenderer(new RNDHTML());
        tblFiles.getColumnModel().getColumn(1).setCellRenderer(new RNDHTML());
        tblFiles.getColumnModel().getColumn(2).setCellRenderer(new RNDHTML());
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jToolBar1 = new JToolBar();
        btnNew = new JButton();
        btnLogout = new JButton();
        lblBW = new JLabel();
        jspFiles = new JScrollPane();
        tblFiles = new JTable();

        //======== this ========

        //======== jToolBar1 ========
        {
            jToolBar1.setFloatable(false);
            jToolBar1.setRollover(true);

            //---- btnNew ----
            btnNew.setIcon(new ImageIcon(getClass().getResource("/artwork/22x22/filenew.png")));
            btnNew.setText("Neu / Upload");
            btnNew.setFocusable(false);
            btnNew.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    btnNewActionPerformed(e);
                }
            });
            jToolBar1.add(btnNew);

            //---- btnLogout ----
            btnLogout.setIcon(new ImageIcon(getClass().getResource("/artwork/22x22/lock.png")));
            btnLogout.setText("Abmelden");
            btnLogout.setFocusable(false);
            btnLogout.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    btnLogoutbtnLogoutHandler(e);
                }
            });
            jToolBar1.add(btnLogout);
        }

        //---- lblBW ----
        lblBW.setFont(new Font("Dialog", Font.BOLD, 18));
        lblBW.setForeground(new Color(255, 51, 0));
        lblBW.setText("jLabel3");

        //======== jspFiles ========
        {
            jspFiles.addComponentListener(new ComponentAdapter() {
                @Override
                public void componentResized(ComponentEvent e) {
                    jspFilesComponentResized(e);
                }
            });

            //---- tblFiles ----
            tblFiles.setModel(new DefaultTableModel(
                new Object[][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                },
                new String[] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ) {
                Class<?>[] columnTypes = new Class<?>[] {
                    Object.class, Object.class, Object.class, Object.class
                };
                @Override
                public Class<?> getColumnClass(int columnIndex) {
                    return columnTypes[columnIndex];
                }
            });
            tblFiles.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            tblFiles.addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent e) {
                    tblFilesMousePressed(e);
                }
            });
            jspFiles.setViewportView(tblFiles);
        }

        GroupLayout layout = new GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup()
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(lblBW, GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                    .addContainerGap())
                .addComponent(jToolBar1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jspFiles, GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                    .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup()
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jToolBar1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblBW, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jspFiles, GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                    .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        new DlgNewFile(parent, bewohner);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnLogoutbtnLogoutHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutbtnLogoutHandler
        OPDE.ocmain.lockOC();
    }//GEN-LAST:event_btnLogoutbtnLogoutHandler

    private void tblFilesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFilesMousePressed

        Point p = evt.getPoint();
        ListSelectionModel lsm = tblFiles.getSelectionModel();

        boolean singleRowSelected = lsm.getMaxSelectionIndex() == lsm.getMinSelectionIndex();

        int row = tblFiles.rowAtPoint(p);
        if (singleRowSelected) {
            lsm.setSelectionInterval(row, row);
        }

        TMSYSFiles tm = (TMSYSFiles) tblFiles.getModel();
        final SYSFiles sysfile = tm.getRow(row);

        if (evt.isPopupTrigger()) {

            SYSTools.unregisterListeners(menu);
            menu = new JPopupMenu();

            // SELECT
            JMenuItem itemPopupShow = new JMenuItem("Anzeigen");
            itemPopupShow.addActionListener(new java.awt.event.ActionListener() {

                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    SYSFilesTools.handleFile(sysfile, Action.OPEN);
                }
            });
            menu.add(itemPopupShow);
            itemPopupShow.setEnabled(OPDE.getInternalClasses().userHasAccessLevelForThisClass(internalClassID, InternalClassACL.SELECT));

            JMenuItem itemPopupDelete = new JMenuItem("Löschen");
            itemPopupDelete.addActionListener(new java.awt.event.ActionListener() {

                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    if (JOptionPane.showConfirmDialog(parent, "Möchten Sie diese Datei wirklich löschen ?",
                            "Datei löschen ?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        SYSFilesTools.deleteFile(sysfile);
                        loadTable();
                    }
                }
            });
            menu.add(itemPopupDelete);
            itemPopupDelete.setEnabled(OPDE.getInternalClasses().userHasAccessLevelForThisClass(internalClassID, InternalClassACL.DELETE));

            menu.show(evt.getComponent(), (int) p.getX(), (int) p.getY());
        } else {
            if (evt.getClickCount() == 2 && OPDE.getInternalClasses().userHasAccessLevelForThisClass(internalClassID, InternalClassACL.SELECT)) { // DoppelClick
                SYSFilesTools.handleFile(sysfile, Action.OPEN);
            }
        }


    }//GEN-LAST:event_tblFilesMousePressed

    private void jspFilesComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jspFilesComponentResized
        JScrollPane jsp = (JScrollPane) evt.getComponent();
        Dimension dim = jsp.getSize();
        // Größe der Text Spalte im TB ändern.
        // Summe der fixen Spalten  = 210 + ein bisschen
        int textWidth = dim.width - 100 - 25;
        tblFiles.getColumnModel().getColumn(0).setPreferredWidth(textWidth / 2);
        tblFiles.getColumnModel().getColumn(1).setPreferredWidth(textWidth / 2);
        tblFiles.getColumnModel().getColumn(2).setPreferredWidth(100);
    }//GEN-LAST:event_jspFilesComponentResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JToolBar jToolBar1;
    private JButton btnNew;
    private JButton btnLogout;
    private JLabel lblBW;
    private JScrollPane jspFiles;
    private JTable tblFiles;
    // End of variables declaration//GEN-END:variables
}
