/*
 * OffenePflege
 * Copyright (C) 2008 Torsten Löhr
 * This program is free software; you can redistribute it and/or modify it under the terms of the 
 * GNU General Public License V2 as published by the Free Software Foundation
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even 
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 * Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with this program; if not, write to 
 * the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110, USA
 * www.offene-pflege.de
 * ------------------------ 
 * Auf deutsch (freie Übersetzung. Rechtlich gilt die englische Version)
 * Dieses Programm ist freie Software. Sie können es unter den Bedingungen der GNU General Public License, 
 * wie von der Free Software Foundation veröffentlicht, weitergeben und/oder modifizieren, gemäß Version 2 der Lizenz.
 *
 * Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen von Nutzen sein wird, aber 
 * OHNE IRGENDEINE GARANTIE, sogar ohne die implizite Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN 
 * BESTIMMTEN ZWECK. Details finden Sie in der GNU General Public License.
 *
 * Sie sollten ein Exemplar der GNU General Public License zusammen mit diesem Programm erhalten haben. Falls nicht, 
 * schreiben Sie an die Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110, USA.
 * 
 */
package op.care.planung;

import java.awt.event.*;
import javax.swing.border.*;
import javax.swing.event.*;
import op.tools.SYSTools;
import tablerenderer.RNDStandard;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import java.awt.*;
import java.awt.event.ComponentEvent;

/**
 * @author root
 */
public class DlgVorlage extends javax.swing.JDialog {

    private ListSelectionListener lsl;
    private long planid;

    /**
     * Creates new form DlgVorlage
     */
    private DlgVorlage(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        SYSTools.centerOnParent(parent, this);
        initDialog();
    }

    private DlgVorlage(JDialog parent) {
        super(parent, true);
        initComponents();
        SYSTools.centerOnParent(parent, this);
        initDialog();
    }

    private void initDialog() {
        setTitle(SYSTools.getWindowTitle("Vorlagen für die Pflegeplanung"));
        reloadTable();
    }

    public static long showDialog(JDialog parent) {
        DlgVorlage dlg = new DlgVorlage(parent);
        dlg.setVisible(true);
        long result = dlg.getPlanid();
        dlg.dispose();
        return result;
    }

    public static long showDialog(Frame parent) {
        DlgVorlage dlg = new DlgVorlage(parent);
        dlg.setVisible(true);
        long result = dlg.getPlanid();
        dlg.dispose();
        return result;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblTitel = new JLabel();
        jPanel1 = new JPanel();
        txtSuche = new JTextField();
        jspVorlagen = new JScrollPane();
        tblVorlagen = new JTable();
        cbAbgesetzte = new JCheckBox();
        jLabel1 = new JLabel();
        btnOK = new JButton();
        btnCancel = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        Container contentPane = getContentPane();

        //---- lblTitel ----
        lblTitel.setFont(new Font("Dialog", Font.BOLD, 18));
        lblTitel.setText("Pflegeplanung aus Vorlage erstellen");

        //======== jPanel1 ========
        {
            jPanel1.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));

            //---- txtSuche ----
            txtSuche.addCaretListener(new CaretListener() {
                @Override
                public void caretUpdate(CaretEvent e) {
                    txtSucheCaretUpdate(e);
                }
            });

            //======== jspVorlagen ========
            {
                jspVorlagen.addComponentListener(new ComponentAdapter() {
                    @Override
                    public void componentResized(ComponentEvent e) {
                        jspVorlagenComponentResized(e);
                    }
                });

                //---- tblVorlagen ----
                tblVorlagen.setModel(new DefaultTableModel(
                    new Object[][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                    },
                    new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                    }
                ));
                tblVorlagen.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        tblVorlagenMouseClicked(e);
                    }
                });
                jspVorlagen.setViewportView(tblVorlagen);
            }

            //---- cbAbgesetzte ----
            cbAbgesetzte.setText("auch abgesetzte anzeigen");
            cbAbgesetzte.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    cbAbgesetzteActionPerformed(e);
                }
            });

            //---- jLabel1 ----
            jLabel1.setText("Stichwort-Suche:");

            GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addComponent(jspVorlagen, GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSuche, GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE))
                            .addComponent(cbAbgesetzte))
                        .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtSuche, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jspVorlagen, GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAbgesetzte)
                        .addContainerGap())
            );
        }

        //---- btnOK ----
        btnOK.setIcon(new ImageIcon(getClass().getResource("/artwork/22x22/apply.png")));
        btnOK.setText("Erstellen");
        btnOK.setEnabled(false);
        btnOK.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnOKActionPerformed(e);
            }
        });

        //---- btnCancel ----
        btnCancel.setIcon(new ImageIcon(getClass().getResource("/artwork/22x22/cancel.png")));
        btnCancel.setText("Abbrechen");
        btnCancel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnCancelActionPerformed(e);
            }
        });

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel1, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(btnOK)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCancel)))
                    .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTitel)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancel)
                        .addComponent(btnOK))
                    .addContainerGap())
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        planid = 0;
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbAbgesetzteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAbgesetzteActionPerformed
        reloadTable();
    }//GEN-LAST:event_cbAbgesetzteActionPerformed

    private void jspVorlagenComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jspVorlagenComponentResized
        JScrollPane jsp = (JScrollPane) evt.getComponent();
        Dimension dim = jsp.getSize();
        // Größe der Text Spalten im DFN ändern.
        // Summe der fixen Spalten  = 175 + ein bisschen
        int textWidth = dim.width - (80 + 80 + 25);
        TableColumnModel tcm1 = tblVorlagen.getColumnModel();
        if (tcm1.getColumnCount() < 4) {
            return;
        }

        tcm1.getColumn(TMVorlagen.COL_STICHWORT).setPreferredWidth(textWidth / 2);
        tcm1.getColumn(TMVorlagen.COL_BWNAME).setPreferredWidth(textWidth / 2);
        tcm1.getColumn(TMVorlagen.COL_VON).setPreferredWidth(80);
        tcm1.getColumn(TMVorlagen.COL_BIS).setPreferredWidth(80);

        tcm1.getColumn(TMVorlagen.COL_STICHWORT).setHeaderValue("Stichwort");
        tcm1.getColumn(TMVorlagen.COL_BWNAME).setHeaderValue("BewohnerIn");
        tcm1.getColumn(TMVorlagen.COL_VON).setHeaderValue("Von");
        tcm1.getColumn(TMVorlagen.COL_BIS).setHeaderValue("Bis");
    }//GEN-LAST:event_jspVorlagenComponentResized

    private void txtSucheCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSucheCaretUpdate
        reloadTable();
    }//GEN-LAST:event_txtSucheCaretUpdate

    private void tblVorlagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVorlagenMouseClicked
        if (evt.getClickCount() == 2) {
            btnOK.doClick();
        }
    }//GEN-LAST:event_tblVorlagenMouseClicked

    private void reloadTable() {
        if (txtSuche.getText().equals("")) {
            tblVorlagen.setModel(new DefaultTableModel());
            return;
        }
        ListSelectionModel lsm = tblVorlagen.getSelectionModel();
        if (lsl != null) {
            lsm.removeListSelectionListener(lsl);
        }
        lsl = new HandleSelections();

        tblVorlagen.setModel(new TMVorlagen(txtSuche.getText(), cbAbgesetzte.isSelected()));
        lsm.addListSelectionListener(lsl);
        tblVorlagen.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jspVorlagen.dispatchEvent(new ComponentEvent(jspVorlagen, ComponentEvent.COMPONENT_RESIZED));
        tblVorlagen.getColumnModel().getColumn(TMVorlagen.COL_STICHWORT).setCellRenderer(new RNDStandard());
        tblVorlagen.getColumnModel().getColumn(TMVorlagen.COL_BWNAME).setCellRenderer(new RNDStandard());
        tblVorlagen.getColumnModel().getColumn(TMVorlagen.COL_VON).setCellRenderer(new RNDStandard());
        tblVorlagen.getColumnModel().getColumn(TMVorlagen.COL_BIS).setCellRenderer(new RNDStandard());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel lblTitel;
    private JPanel jPanel1;
    private JTextField txtSuche;
    private JScrollPane jspVorlagen;
    private JTable tblVorlagen;
    private JCheckBox cbAbgesetzte;
    private JLabel jLabel1;
    private JButton btnOK;
    private JButton btnCancel;
    // End of variables declaration//GEN-END:variables
    public long getPlanid() {
        return planid;
    }

    // End of variables declaration
    class HandleSelections
            implements ListSelectionListener {

        public void valueChanged(ListSelectionEvent lse) {
            TableModel tm = tblVorlagen.getModel();
            if (tm.getRowCount() <= 0) {
                return;
            }

            if (!lse.getValueIsAdjusting()) {
                DefaultListSelectionModel lsm = (DefaultListSelectionModel) lse.getSource();
                if (lsm.isSelectionEmpty()) {
                    btnOK.setEnabled(false);
                    planid = 0;
                } else {
                    planid = ((Long) tm.getValueAt(lsm.getLeadSelectionIndex(), TMVorlagen.COL_PLANID)).longValue();
                    btnOK.setEnabled(true);
                }
                //if (ts.)
            }

        }
    }
}
