/*
 * OffenePflege
 * Copyright (C) 2008 Torsten Löhr
 * This program is free software; you can redistribute it and/or modify it under the terms of the 
 * GNU General Public License V2 as published by the Free Software Foundation
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even 
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 * Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with this program; if not, write to 
 * the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110, USA
 * www.offene-pflege.de
 * ------------------------ 
 * Auf deutsch (freie Übersetzung. Rechtlich gilt die englische Version)
 * Dieses Programm ist freie Software. Sie können es unter den Bedingungen der GNU General Public License, 
 * wie von der Free Software Foundation veröffentlicht, weitergeben und/oder modifizieren, gemäß Version 2 der Lizenz.
 *
 * Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen von Nutzen sein wird, aber 
 * OHNE IRGENDEINE GARANTIE, sogar ohne die implizite Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN 
 * BESTIMMTEN ZWECK. Details finden Sie in der GNU General Public License.
 *
 * Sie sollten ein Exemplar der GNU General Public License zusammen mit diesem Programm erhalten haben. Falls nicht, 
 * schreiben Sie an die Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110, USA.
 * 
 */
package op.care.planung;

import op.tools.SYSTools;
import tablerenderer.RNDStandard;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import java.awt.*;
import java.awt.event.ComponentEvent;

/**
 * @author root
 */
public class DlgVorlage extends javax.swing.JDialog {

    private ListSelectionListener lsl;
    private long planid;

    /**
     * Creates new form DlgVorlage
     */
    private DlgVorlage(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        SYSTools.centerOnParent(parent, this);
        initDialog();
    }

    private DlgVorlage(JDialog parent) {
        super(parent, true);
        initComponents();
        SYSTools.centerOnParent(parent, this);
        initDialog();
    }

    private void initDialog() {
        setTitle(SYSTools.getWindowTitle("Vorlagen für die Pflegeplanung"));
        reloadTable();
    }

    public static long showDialog(JDialog parent) {
        DlgVorlage dlg = new DlgVorlage(parent);
        dlg.setVisible(true);
        long result = dlg.getPlanid();
        dlg.dispose();
        return result;
    }

    public static long showDialog(Frame parent) {
        DlgVorlage dlg = new DlgVorlage(parent);
        dlg.setVisible(true);
        long result = dlg.getPlanid();
        dlg.dispose();
        return result;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtSuche = new javax.swing.JTextField();
        jspVorlagen = new javax.swing.JScrollPane();
        tblVorlagen = new javax.swing.JTable();
        cbAbgesetzte = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitel.setFont(new java.awt.Font("Dialog", 1, 18));
        lblTitel.setText("Pflegeplanung aus Vorlage erstellen");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtSuche.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSucheCaretUpdate(evt);
            }
        });

        jspVorlagen.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jspVorlagenComponentResized(evt);
            }
        });

        tblVorlagen.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        tblVorlagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVorlagenMouseClicked(evt);
            }
        });
        jspVorlagen.setViewportView(tblVorlagen);

        cbAbgesetzte.setText("auch abgesetzte anzeigen");
        cbAbgesetzte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAbgesetzteActionPerformed(evt);
            }
        });

        jLabel1.setText("Stichwort-Suche:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jspVorlagen, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtSuche, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE))
                                        .addComponent(cbAbgesetzte))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtSuche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jspVorlagen, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbAbgesetzte)
                                .addContainerGap())
        );

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artwork/22x22/apply.png"))); // NOI18N
        btnOK.setText("Erstellen");
        btnOK.setEnabled(false);
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artwork/22x22/cancel.png"))); // NOI18N
        btnCancel.setText("Abbrechen");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTitel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnOK)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnCancel)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTitel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCancel)
                                        .addComponent(btnOK))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        planid = 0;
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbAbgesetzteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAbgesetzteActionPerformed
        reloadTable();
    }//GEN-LAST:event_cbAbgesetzteActionPerformed

    private void jspVorlagenComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jspVorlagenComponentResized
        JScrollPane jsp = (JScrollPane) evt.getComponent();
        Dimension dim = jsp.getSize();
        // Größe der Text Spalten im DFN ändern.
        // Summe der fixen Spalten  = 175 + ein bisschen
        int textWidth = dim.width - (80 + 80 + 25);
        TableColumnModel tcm1 = tblVorlagen.getColumnModel();
        if (tcm1.getColumnCount() < 4) {
            return;
        }

        tcm1.getColumn(TMVorlagen.COL_STICHWORT).setPreferredWidth(textWidth / 2);
        tcm1.getColumn(TMVorlagen.COL_BWNAME).setPreferredWidth(textWidth / 2);
        tcm1.getColumn(TMVorlagen.COL_VON).setPreferredWidth(80);
        tcm1.getColumn(TMVorlagen.COL_BIS).setPreferredWidth(80);

        tcm1.getColumn(TMVorlagen.COL_STICHWORT).setHeaderValue("Stichwort");
        tcm1.getColumn(TMVorlagen.COL_BWNAME).setHeaderValue("BewohnerIn");
        tcm1.getColumn(TMVorlagen.COL_VON).setHeaderValue("Von");
        tcm1.getColumn(TMVorlagen.COL_BIS).setHeaderValue("Bis");
    }//GEN-LAST:event_jspVorlagenComponentResized

    private void txtSucheCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSucheCaretUpdate
        reloadTable();
    }//GEN-LAST:event_txtSucheCaretUpdate

    private void tblVorlagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVorlagenMouseClicked
        if (evt.getClickCount() == 2) {
            btnOK.doClick();
        }
    }//GEN-LAST:event_tblVorlagenMouseClicked

    private void reloadTable() {
        if (txtSuche.getText().equals("")) {
            tblVorlagen.setModel(new DefaultTableModel());
            return;
        }
        ListSelectionModel lsm = tblVorlagen.getSelectionModel();
        if (lsl != null) {
            lsm.removeListSelectionListener(lsl);
        }
        lsl = new HandleSelections();

        tblVorlagen.setModel(new TMVorlagen(txtSuche.getText(), cbAbgesetzte.isSelected()));
        lsm.addListSelectionListener(lsl);
        tblVorlagen.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jspVorlagen.dispatchEvent(new ComponentEvent(jspVorlagen, ComponentEvent.COMPONENT_RESIZED));
        tblVorlagen.getColumnModel().getColumn(TMVorlagen.COL_STICHWORT).setCellRenderer(new RNDStandard());
        tblVorlagen.getColumnModel().getColumn(TMVorlagen.COL_BWNAME).setCellRenderer(new RNDStandard());
        tblVorlagen.getColumnModel().getColumn(TMVorlagen.COL_VON).setCellRenderer(new RNDStandard());
        tblVorlagen.getColumnModel().getColumn(TMVorlagen.COL_BIS).setCellRenderer(new RNDStandard());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JCheckBox cbAbgesetzte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jspVorlagen;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JTable tblVorlagen;
    private javax.swing.JTextField txtSuche;

    // End of variables declaration//GEN-END:variables
    public long getPlanid() {
        return planid;
    }

    // End of variables declaration
    class HandleSelections
            implements ListSelectionListener {

        public void valueChanged(ListSelectionEvent lse) {
            TableModel tm = tblVorlagen.getModel();
            if (tm.getRowCount() <= 0) {
                return;
            }

            if (!lse.getValueIsAdjusting()) {
                DefaultListSelectionModel lsm = (DefaultListSelectionModel) lse.getSource();
                if (lsm.isSelectionEmpty()) {
                    btnOK.setEnabled(false);
                    planid = 0;
                } else {
                    planid = ((Long) tm.getValueAt(lsm.getLeadSelectionIndex(), TMVorlagen.COL_PLANID)).longValue();
                    btnOK.setEnabled(true);
                }
                //if (ts.)
            }

        }
    }
}
