/*
 * OffenePflege
 * Copyright (C) 2008 Torsten Löhr
 * This program is free software; you can redistribute it and/or modify it under the terms of the 
 * GNU General Public License V2 as published by the Free Software Foundation
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even 
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 * Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with this program; if not, write to 
 * the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110, USA
 * www.offene-pflege.de
 * ------------------------ 
 * Auf deutsch (freie Übersetzung. Rechtlich gilt die englische Version)
 * Dieses Programm ist freie Software. Sie können es unter den Bedingungen der GNU General Public License, 
 * wie von der Free Software Foundation veröffentlicht, weitergeben und/oder modifizieren, gemäß Version 2 der Lizenz.
 *
 * Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen von Nutzen sein wird, aber 
 * OHNE IRGENDEINE GARANTIE, sogar ohne die implizite Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN 
 * BESTIMMTEN ZWECK. Details finden Sie in der GNU General Public License.
 *
 * Sie sollten ein Exemplar der GNU General Public License zusammen mit diesem Programm erhalten haben. Falls nicht, 
 * schreiben Sie an die Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110, USA.
 */
package op.system;

import java.awt.event.*;
import entity.system.SYSLoginTools;
import op.OPDE;
import op.threads.DisplayMessage;
import op.tools.MyJDialog;
import op.tools.SYSTools;
import org.apache.commons.collections.Closure;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.SQLException;

/**
 * @author __USER__
 */
public class DlgLogin extends MyJDialog {

    //    Thread thread = null;
    private Closure actionBlock;

    /**
     * Creates new form DlgLogin
     */
    private void thisWindowClosing(WindowEvent e) {
        // TODO add your code here
    }

    public DlgLogin(Closure actionBlock) {
        super(OPDE.getMainframe());
        OPDE.setLogin(null);
        this.actionBlock = actionBlock;

        try {
            if (OPDE.getDb() != null && !OPDE.getDb().db.isClosed()) {
                OPDE.getDb().db.close();
            }
        } catch (SQLException se) {
            System.out.println(se.getMessage());
        }

        initComponents();
//        lblMessage.setText(SYSTools.catchNull(preMessage));

        String defaultlogin = "";

        String defaultpw = "";
        if (OPDE.getLocalProps().containsKey("defaultlogin")) {
            defaultlogin = OPDE.getLocalProps().getProperty("defaultlogin");
        }
        if (OPDE.getLocalProps().containsKey("defaultpw")) {
            defaultpw = OPDE.getLocalProps().getProperty("defaultpw");
        }
        txtUsername.setText(defaultlogin);
        txtPassword.setText(defaultpw);

//        try {
//            linkOPDE.setURI(new URI("http://www.offene-pflege.de"));
//            linkOPDE.setText("Offene-Pflege.de");
//        } catch (URISyntaxException ex) {
//            new DlgException(ex);
//        }

        txtUsername.requestFocus();
        pack();
//        SYSTools.centerOnParent(parent, this);
//        btnAbout.setIcon(new ImageIcon(getClass().getResource("/artwork/animation/opde-52.png")));
//        setVisible(true);

    }


//    private void animateLogo() {
//        thread = new Thread() {
//
//            public void run() {
//
//                int maxIconsNum = 85;
//
//                try {
//                    int i = 0;
//                    while (true) {
//                        if (i == OPDE.getAnimationCache().size()) {
//                            OPDE.getAnimationCache().add(new ImageIcon(getClass().getResource("/artwork/animation/opde-" + (i + 1) + ".png")));
//                        }
//                        btnAbout.setIcon(OPDE.getAnimationCache().get(i));
//
//                        Thread.sleep(55);
//                        if (i == maxIconsNum) {
//                            i = 0;
//                        } else {
//                            i++;
//                        }
//                    }
//                } catch (InterruptedException e) {
//                }
//            }
//        };
//        thread.start();
//    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        btnLogin = new JButton();
        jPanel1 = new JPanel();
        jLabel2 = new JLabel();
        txtUsername = new JTextField();
        jLabel1 = new JLabel();
        txtPassword = new JPasswordField();
        jPanel2 = new JPanel();
        btnAbout = new JButton();
        jLabel4 = new JLabel();
        lblOPDE = new JLabel();

        //======== this ========
        setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        setResizable(false);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                thisWindowClosing(e);
            }
        });
        Container contentPane = getContentPane();

        //---- btnLogin ----
        btnLogin.setIcon(new ImageIcon(getClass().getResource("/artwork/22x22/apply.png")));
        btnLogin.setText("Anmelden");
        btnLogin.setActionCommand("btnLogin");
        btnLogin.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DoLogin(e);
            }
        });

        //======== jPanel1 ========
        {
            jPanel1.setBorder(new EmptyBorder(5, 5, 5, 5));
            jPanel1.setOpaque(false);

            //---- jLabel2 ----
            jLabel2.setText("Benutzername");

            //---- txtUsername ----
            txtUsername.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    txtUsernameActionPerformed(e);
                }
            });
            txtUsername.addFocusListener(new FocusAdapter() {
                @Override
                public void focusGained(FocusEvent e) {
                    txtUsernameFocusGained(e);
                }
            });

            //---- jLabel1 ----
            jLabel1.setText("Passwort");
            jLabel1.setPreferredSize(new Dimension(4, 19));

            //---- txtPassword ----
            txtPassword.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    txtPasswordActionPerformed(e);
                }
            });
            txtPassword.addFocusListener(new FocusAdapter() {
                @Override
                public void focusGained(FocusEvent e) {
                    txtPasswordFocusGained(e);
                }
            });

            GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addComponent(txtPassword, GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                            .addComponent(txtUsername, GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                        .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
            );
            jPanel1Layout.linkSize(SwingConstants.VERTICAL, new Component[] {jLabel1, jLabel2});
        }

        //======== jPanel2 ========
        {
            jPanel2.setBorder(new EmptyBorder(5, 5, 5, 5));
            jPanel2.setOpaque(false);

            //---- btnAbout ----
            btnAbout.setIcon(new ImageIcon(getClass().getResource("/artwork/64x64/opde-metal.png")));
            btnAbout.setToolTipText("\u00dcber Offene-Pflege.de...");
            btnAbout.setBorderPainted(false);
            btnAbout.setBorder(null);
            btnAbout.setOpaque(false);
            btnAbout.setContentAreaFilled(false);
            btnAbout.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    btnAboutActionPerformed(e);
                }
            });

            //---- jLabel4 ----
            jLabel4.setFont(new Font("Arial", Font.PLAIN, 13));
            jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
            jLabel4.setText("So viel Pflege wie m\u00f6glich, so viel Technik wie n\u00f6tig. ");

            //---- lblOPDE ----
            lblOPDE.setText("Offene-Pflege.de");
            lblOPDE.setFont(new Font("Arial", Font.PLAIN, 24));
            lblOPDE.setHorizontalAlignment(SwingConstants.CENTER);

            GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup()
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAbout, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblOPDE, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 314, GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup()
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup()
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAbout, GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblOPDE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addContainerGap())
            );
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel2, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                                .addComponent(jPanel1, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(btnLogin))
                    .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnLogin)
                    .addContainerGap())
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        ((JTextField) evt.getSource()).selectAll();
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        ((JTextField) evt.getSource()).selectAll();
    }//GEN-LAST:event_txtUsernameFocusGained


    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        btnLogin.doClick();
    }//GEN-LAST:event_txtPasswordActionPerformed

    @Override
    public void dispose() {
        actionBlock.execute(OPDE.getLogin());
        SYSTools.unregisterListeners(this);
        super.dispose();
    }

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        txtPassword.requestFocus();
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void DoLogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoLogin
        String username = txtUsername.getText().trim();
//            char[] password = txtPassword.getPassword();

        try {

            OPDE.initDB();

            // Hier wird erst geprüft, ob Username und Passwort stimmen.
            registerLogin();
            if (OPDE.getLogin() == null) {
                OPDE.getDisplayManager().addSubMessage(new DisplayMessage("Benutzername oder Passwort falsch.", 2));
                OPDE.info("Falsches Passwort eingegeben.");
            } else {

                OPDE.newOCSec();

                OPDE.initProps();

                OPDE.info("Anmeldung erfolgt: UKennung: " + username);
                OPDE.info("LoginID: " + OPDE.getLogin().getUser().getUKennung());

                dispose();
            }

        } catch (SQLException se) {
            OPDE.fatal(se);
            System.exit(se.getErrorCode());
        }
    }//GEN-LAST:event_DoLogin

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI("http://www.offene-pflege.de"));
            } catch (IOException ioe) {
                ioe.printStackTrace();
            } catch (URISyntaxException use) {
                use.printStackTrace();

            }
        }
    }//GEN-LAST:event_btnAboutActionPerformed

    /**
     * Trägt ein DlgLogin ein. Es werden alte, zerstörte DlgLogin Reste ebenfalls entfernt und zwar nach dem folgendem Muster:
     * <p/>
     * <li>	Es wird nach DlgLogin Einträgen gesucht, bei denen LOGOUT auf BAW steht. Das bedeutet, dass sie bei der letzten Anmeldung nicht ordnungsgemäß
     * abgeschlossen wurden. Bei diesen Records wird Logout auf LPOL gesetzt. Was ja auch halbwegs der Wahrheit entspricht. Die Sitzung war beendet
     * als die Station abstürzte und das wiederum war kurz nach dem letzten Lebenszeichen.</li>
     * <p/>
     * <li> Alle WorkingOn Einträge dieser (kaputten) LoginID werden auf LPOL gesetzt. Liegt LPOL allerdings weniger als <b>2 Minuten zurück</b>, dann wird
     * der Eintrag verweigert. Dann läuft wohl noch eine andere Sitzung.</li>
     *
     * @return true, wenn die Anmeldung erlaubt ist, false, wenn man noch warten muss.
     */
    private void registerLogin() {
        //long loginid;
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());

        OPDE.setLogin(SYSLoginTools.login(username, password));
//
//        try {
//
//
//            // Gibt es noch laufende Sitzungen, die sich innerhalb der vergangenen 2 Minuten als
//            // lebendig gemeldet haben ?
////            String sqlRunningSessions = "SELECT OCLoginID FROM OCLogin "
////                    + "WHERE UKennung=? AND IP=? AND Logout='9999-12-31 23:59:59' AND DATE_ADD(LPOL,INTERVAL 2 MINUTE) > now()";
////            PreparedStatement stmt = OPDE.getDb().db.prepareStatement(sqlRunningSessions);
////            stmt.setString(1, username);
////            stmt.setString(2, OPDE.getProps().getProperty("ip"));
////            ResultSet rsRunningSessions = stmt.executeQuery();
//
////            if (!rsRunningSessions.first()) { // Die Luft ist rein.... Schnell anmelden ;-)
////                String sqlNewSession = "INSERT INTO OCLogin (UKennung, HOST, IP, Login, LPOL, Logout) VALUES (?, ?, ?, NOW(), NOW(), '9999-12-31 23:59:59')";
////                PreparedStatement stmtNewSession = OPDE.getDb().db.prepareStatement(sqlNewSession);
////                stmtNewSession.setString(1, username);
////                stmtNewSession.setString(2, OPDE.getLocalProps().getProperty("hostname"));
////                stmtNewSession.setString(3, OPDE.getLocalProps().getProperty("ip"));
////                stmtNewSession.executeUpdate();
////
////                loginid = OPDE.getDb().getLastInsertedID();
//
//            // Aufräumen
//            // Zuerst OCWorkingOn von alten Trümmer Einträgen befreien.
////                String sqlWOCleanupSession = "UPDATE OCWorkingOn SET Finish=NOW()  WHERE OCLoginID IN ( SELECT OCLoginID FROM OCLogin WHERE Logout='9999-12-31 23:59:59' AND DATE_ADD(LPOL,INTERVAL 3 MINUTE) <= now() )";
////                PreparedStatement stmtWOCleanupSession = OPDE.getDb().db.prepareStatement(sqlWOCleanupSession);
////                stmtWOCleanupSession.executeUpdate();
////
////                // OCMessages löschen, die von toten Logins stammen. Damit ein evtl. BHPImport nicht ewig darauf wartet.
////                String sqlMessageCleanupSession = "DELETE FROM OCMessage WHERE Receiver IN ( SELECT OCLoginID FROM OCLogin WHERE Logout='9999-12-31 23:59:59' AND DATE_ADD(LPOL,INTERVAL 3 MINUTE) <= now() )";
////                PreparedStatement stmtMessageCleanupSession = OPDE.getDb().db.prepareStatement(sqlMessageCleanupSession);
////                stmtMessageCleanupSession.executeUpdate();
//
////            // Dann Verordnungen zur BHP, die aus alten Trümmersitzungen stammen löschen.
////            String sqlBHPCleanupSession = "DELETE FROM BHPPlanung WHERE tmp IN ( SELECT l.LoginID FROM SYSLogin l INNER JOIN SYSHosts h ON l.HostID = h.HostID WHERE l.Logout='9999-12-31 23:59:59' AND DATE_ADD(h.LPOL,INTERVAL 3 MINUTE) <= now() )";
////            PreparedStatement stmtBHPCleanupSession = OPDE.getDb().db.prepareStatement(sqlBHPCleanupSession);
////            stmtBHPCleanupSession.executeUpdate();
////
////            // Dann MassTermine löschen, die aus alten Trümmersitzungen stammen löschen.
////            String sqlMassTerminCleanupSession = "DELETE FROM MassTermin WHERE tmp IN ( SELECT l.LoginID FROM SYSLogin l INNER JOIN SYSHosts h ON l.HostID = h.HostID WHERE l.Logout='9999-12-31 23:59:59' AND DATE_ADD(h.LPOL,INTERVAL 3 MINUTE) <= now() )";
////            PreparedStatement stmtMassTerminCleanupSession = OPDE.getDb().db.prepareStatement(sqlMassTerminCleanupSession);
////            stmtMassTerminCleanupSession.executeUpdate();
//
//            // Dann OCLogin bereinigen.
////            String sqlCleanupSession = "UPDATE SYSLogin l INNER JOIN SYSHosts h ON l.HostID = h.HostID SET l.Logout=LPOL WHERE l.Logout='9999-12-31 23:59:59' AND DATE_ADD(h.LPOL,INTERVAL 3 MINUTE) <= now()";
////            PreparedStatement stmtCleanupSession = OPDE.getDb().db.prepareStatement(sqlCleanupSession);
////            stmtCleanupSession.executeUpdate();
//
////            } else {
////                JOptionPane.showMessageDialog(this, "Sie sind bereits an diesem Computer angemeldet.\n\nFalls Sie den Rechner gerade neu gestartet haben,\ndann warten Sie ca. 1 Minute und versuchen es dann nochmal.", "Anmeldefehler", JOptionPane.INFORMATION_MESSAGE);
////                loginid = 0;
////            }
//        } // try
//        catch (Exception se) {
//            OPDE.fatal(se);
//        } // catch
        //return (loginid);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnLogin;
    private JPanel jPanel1;
    private JLabel jLabel2;
    private JTextField txtUsername;
    private JLabel jLabel1;
    private JPasswordField txtPassword;
    private JPanel jPanel2;
    private JButton btnAbout;
    private JLabel jLabel4;
    private JLabel lblOPDE;
    // End of variables declaration//GEN-END:variables
}
