/*
 * DlgNode.java
 *
 * Created on 17. November 2008, 13:54
 */
package op.care.planung.massnahmen;

import java.awt.Component;
import java.awt.Frame;
import javax.swing.JDialog;
import op.tools.SYSTools;

/**
 *
 * @author  tloehr
 */
public class DlgNode extends javax.swing.JDialog {

    private Component parent;
    private Object[] data;
    private double prozent;
    private double zeit;
    private boolean ignoreZeitUpdate = false,  ignoreProzentUpdate = false;

    /** Creates new form DlgNode */
    public DlgNode(Frame parent, Object[] data) {
        super(parent, true);
        this.data = data;
        this.parent = parent;
        initDialog();
    }

    public DlgNode(JDialog parent, Object[] data) {
        super(parent, true);
        this.data = data;
        this.parent = parent;
        initDialog();
    }

    private void initDialog() {
        initComponents();

        int typ = (Integer) data[0];
        String mode = "";
        if (data[1] == null) {
            mode = " (Neu)";
            txtBeschreibung.setText("");
            txtBezeichnung.setText("");
            txtProzent.setText("0");
            txtZeit.setText("0");
        } else {
            mode = " (Bearbeitung)";
            txtBezeichnung.setText(SYSTools.catchNull(data[1]));
            txtBeschreibung.setText(SYSTools.catchNull(data[2]));
            zeit = 0d;
            if (data[3] != null) {
                zeit = (Double) data[3];
            }
            prozent = 0d;
            if (data[4] != null) {
                prozent = (Double) data[4];
            }
            ignoreProzentUpdate = true;
            ignoreZeitUpdate = true;
            txtZeit.setText(Double.toString(zeit));
            txtProzent.setText(Double.toString(prozent));
            ignoreProzentUpdate = false;
            ignoreZeitUpdate = false;
        }

        txtProzent.setEnabled(typ == ParserMassnahmen.TYPE_MODFAKTOR);
        lblProzent.setEnabled(typ == ParserMassnahmen.TYPE_MODFAKTOR);
        String title = ParserMassnahmen.getNodeTypeName(typ);


        lblTyp.setText(title + mode);
        setTitle(SYSTools.getWindowTitle(title));
    }

    public Object[] showDialog() {
        SYSTools.centerOnParent(parent, this);
        setVisible(true);
        return data;
    }

    private void saveOK() {
        prozent = 0d;
        zeit = 0d;

        boolean prozentOK = false;
        boolean zeitOK = false;


        try {
            String test = txtProzent.getText();
            test = test.replace(",", ".");
            prozent = Double.parseDouble(test);
            prozentOK = true;
        } catch (NumberFormatException nfe) {
            prozentOK = false;
            prozent = 0d;
        }

        try {
            String test = txtZeit.getText();
            test = test.replace(",", ".");
            zeit = Double.parseDouble(test);
            zeitOK = true;
        } catch (NumberFormatException nfe) {
            zeitOK = false;
            zeit = 0d;
        }

        boolean bezeichnungOK = !txtBezeichnung.equals("");

        btnOK.setEnabled((prozentOK || zeitOK) && bezeichnungOK);

        if (!btnOK.isEnabled()) {
            String ursache = "<html><body>Es fehlen noch Angaben, bevor Sie speichern können.<ul>";
            ursache += (prozentOK ? "" : "<li>Die Prozentangabe ist fehlerhaft.</li>");
            ursache += (zeitOK ? "" : "<li>Die Zeitangabge ist fehlerhaft.</li>");
            ursache += (bezeichnungOK ? "" : "<li>Sie müssen eine Bezeichnung für das Element eingeben.</li>");
            ursache += "</ul></body></html>";
            btnOK.setToolTipText(ursache);
        } else {
            btnOK.setToolTipText(null);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTyp = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBezeichnung = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBeschreibung = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        txtZeit = new javax.swing.JTextField();
        lblProzent = new javax.swing.JLabel();
        txtProzent = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblTyp.setFont(new java.awt.Font("Dialog", 1, 18));
        lblTyp.setText("Typ: Teilschritt (Neu)");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Bezeichnung:");

        jLabel3.setText("Beschreibung:");

        txtBezeichnung.setText("jTextField1");

        jScrollPane1.setViewportView(txtBeschreibung);

        jLabel4.setText("Zeit:");

        txtZeit.setToolTipText("in Minuten");
        txtZeit.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtZeitCaretUpdate(evt);
            }
        });

        lblProzent.setText("Prozent:");

        txtProzent.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtProzentCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(txtBezeichnung, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtZeit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(lblProzent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProzent, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtProzent, txtZeit});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBezeichnung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtZeit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtProzent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblProzent)))
                .addContainerGap())
        );

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artwork/22x22/cancel.png"))); // NOI18N
        btnCancel.setText("Abbrechen");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artwork/22x22/apply.png"))); // NOI18N
        btnOK.setText("Übernehmen");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTyp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTyp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtZeitCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtZeitCaretUpdate
    if (!ignoreZeitUpdate) {
        ignoreProzentUpdate = true;
        txtProzent.setText("");
        saveOK();
        ignoreProzentUpdate = false;
    }
    }//GEN-LAST:event_txtZeitCaretUpdate

private void txtProzentCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtProzentCaretUpdate
    if (!ignoreProzentUpdate) {
        ignoreZeitUpdate = true;
        txtZeit.setText("");
        saveOK();
        ignoreZeitUpdate = false;
    }
    }//GEN-LAST:event_txtProzentCaretUpdate

private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

    data = null;
    dispose();

    }//GEN-LAST:event_btnCancelActionPerformed

private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
    data[1] = txtBezeichnung.getText();
    data[2] = txtBeschreibung.getText();
    data[3] = new Double(zeit);
    data[4] = new Double(prozent);
    setVisible(false);
    }//GEN-LAST:event_btnOKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProzent;
    private javax.swing.JLabel lblTyp;
    private javax.swing.JTextPane txtBeschreibung;
    private javax.swing.JTextField txtBezeichnung;
    private javax.swing.JTextField txtProzent;
    private javax.swing.JTextField txtZeit;
    // End of variables declaration//GEN-END:variables
}
